export default {
  day: require("../assets/bg_day.png"),
  night: require("../assets/bg_night.png"),
  land: require("../assets/land.png"),
  bird0: require("../assets/bird0_0.png"),
  bird1: require("../assets/bird0_1.png"),
  bird2: require("../assets/bird0_2.png"),
  blink0: require("../assets/blink_00.png"),
  blink1: require("../assets/blink_01.png"),
  blink2: require("../assets/blink_02.png"),
  copyright: require("../assets/brand_copyright.png"),
  button_play: require("../assets/button_play.png"),
  title: require("../assets/title.png"),
  tutorial: require("../assets/tutorial.png"),
  pipeDown: require("../assets/pipe_down.png"),
  pipeUp: require("../assets/pipe_up.png"),
  0: require("../assets/font_048.png"),
  1: require("../assets/font_049.png"),
  2: require("../assets/font_050.png"),
  3: require("../assets/font_051.png"),
  4: require("../assets/font_052.png"),
  5: require("../assets/font_053.png"),
  6: require("../assets/font_054.png"),
  7: require("../assets/font_055.png"),
  8: require("../assets/font_056.png"),
  9: require("../assets/font_057.png"),
};
